### ISSUE TITLE
Beschränkung Zahllänge

### ISSUE THREAD

**Issue by vinkja** [ibwgr/Tarif-Erfassungs-System#60]
Beschränke die ausgerechnete Summe auf zwei Kommazahlen. Ansonsten übersprengt es die Tabelle.

First comes first servers

**Comment by sascha1987** [comment]
Also nur die ausgerechnete Summe müsste mit:
return Math.round(result * 100) / 100
funktionieren.

**Comment by nadavisuals** [comment]
Ich habe noch den Ansatz verfolgt schon die Eingabe auf 2 Dezimalstellen zu beschränken. Hat bis jetzt nur teilweise funktioniert. Habe euch ein Mail geschickt mit den Details. Vielleicht habt ihr noch eine Idee.
